### ISSUE TITLE
Rebuild CSS

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange-hugo#187]
PR #186 did not rebuild the css files and I wanted to do it now, but I could not.

On my system, `npm install` fails. I tried installing packages manually, but there was a problem installing autoprefixer. I have node v8.10.0 and npm v3.5.2. @mitjapotocin, should this work?

```
npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
```

I get the same issue when installing autoprefixer. Some other packages work though.

**Comment by mitjapotocin** [comment]
Those node and npm versions are a bit outdated, try updating, or you can try installing with yarn.
